### ISSUE TITLE
Question : Is there a way to avoid page flicker on clicking/changing tabs? 

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterApps/Website#62] opened 2017-03-11 02:22 UTC
### Steps to reproduce
go to http://localhost:8080/website
Click `Bleeding Points`

### Expected result
The Page should render without flickering. Or there should be an option to display loading icon

### Actual result
The html is refreshed, so the page flickers. In this example it does not flicker alot, but In my repo, I have pages with much more delay.

##### Starcounter version 
2.3.0.5828

##### Involved apps' version
1. SignIn (synced with the latest commit in develop branch)
2. UserAdmin (synced with the latest commit in develop branch)
3. WebSite (synced with the latest commit in develop branch)

##### Browsers affected

- [ ] Chrome

### Screenshot
1. 
![image](https://cloud.githubusercontent.com/assets/4388707/23819653/8b2fd63a-0609-11e7-8933-6ce42005fa60.png)

2.
![image](https://cloud.githubusercontent.com/assets/4388707/23819686/dac5d00a-0609-11e7-8dac-5112545c9967.png)

3. 
![image](https://cloud.githubusercontent.com/assets/4388707/23819659/a3a154c8-0609-11e7-839d-ce25a58106c7.png)

**Comment by PatrykSzwer** [comment] 2017-06-22 09:56
Could You please check if It's still happening and update this issue? And if It's still reproducible, could You provide some video or more details? Because I'm not sure what "flickering" u were writing about.

**Comment by warpech** [comment] 2017-06-22 11:39
This is related to #55 and should be worked on together.

**Comment by PatrykSzwer** [comment] 2017-06-28 10:54
This issue is not reproducible anymore. After discussion with @un-tone we decided to close it.

**Closed by PatrykSzwer** 2017-06-28 10:54 UTC
Labels: enhancement
