### ISSUE TITLE
Broken integration with Content app

### ISSUE THREAD

**Issue by Mihaiii** [StarcounterApps/Website#154] opened 2017-07-28 15:49 UTC
### Steps to reproduce
1. Run in debugging mode [Content app](https://github.com/StarcounterApps/Content) at https://github.com/StarcounterApps/Content/pull/92/commits/89c69d359f48dda2d4beb3768c4e7dcf71ef9c2d .
2. Run Website at  77cbcd865ab1891e26b265426bf954123e57ee35 .
3. Run Sign In at https://github.com/StarcounterApps/SignIn/commit/bb24f80f31f59a80b925d4b382edaa133f0d9cb9
4. Put a breakpoint [here](https://github.com/StarcounterApps/Content/pull/92/commits/89c69d359f48dda2d4beb3768c4e7dcf71ef9c2d#diff-ccd4cf3920c56e95dcc937e7fa590631L17) .
5. Go to `http://localhost:8080/resetdata` -> `http://localhost:8080/websiteeditor` -> "DefaultSurface" -> "Blending points" and replace for "TopBar" the "Pin URI" from `/signin/user` to `/content/dynamic/something`.

### Expected result
Hit the breakpoint.

### Actual result
It doesn't hit the breakpoint.

### More Info
It works fine for `/signin/user` or `/signin/profile`.
**Update: doesn't work with `/signin/signinuser?something`**

##### Starcounter version 
SC 2.3.1.6852

@alemoi , @un-tone Can you help with this one?

**Comment by un-tone** [comment] 2017-07-31 07:50
I'll check it

**Comment by un-tone** [comment] 2017-07-31 09:00
I see the following case:
 - Content app has a handler for `/content/dynamic/{?}` URI which accept `/content/dynamic/something` requests.
 - Blender mapped this URI correctly:
```
Blender.ListForSpecificUri("/websiteprovider/blender/surface/y/point/z").Select(x => x.Uri)
    [0]: "/content/dynamic/something"
    [1]: "/websiteprovider/blender/surface/y/point/z"
```
Website calls `/websiteprovider/blender/surface/y/point/z` URI to get content for "TopBar".

-----

Blender expects `/content/dynamic/{?}` to be mapped -- it cannot blend just `/content/dynamic/something` since this URI is not registered with Handler.
There is a problem for Website app, it definitely should be able to map such URIs as expected.

@alemoi is it possible do something with it on the Blender side? If no, I suppose I'll have to wrap such custom URIs callings into another dynamically created one. I wouldn't do so since it will add complexity to pinning rules mapping logic.

**Comment by alemoi** [comment] 2017-07-31 09:35
@un-tone I didn't really get this one. So its a concrete URI that is mapped not a handler template?

**Comment by un-tone** [comment] 2017-07-31 09:52
Yes. I will try to detail. We have:

- Registered handler:
```csharp
Handle.GET("/content/dynamic/{?}", (Request req, string query) => { ... }
```

- Mapped URIs with `websiteprovider%y%z` token:
  - `/content/dynamic/something`
  - `/websiteprovider/blender/surface/y/point/z`

- Website calls `Self.GET("/websiteprovider/blender/surface/y/point/z")`

In this case we want that `/content/dynamic/{?}` handler with `something` parameter will be called.

**Comment by alemoi** [comment] 2017-07-31 13:21
Thank you! Now I understand the question. Blending is done on handlers, so to blend a certain URI, you should do a blender on handler `/content/dynamic/{?}`, check needed parameters in the "from" converter and return non-null string parameters. From documentation (https://docs.starcounter.io/guides/blending/blending/):
```
Often it's needed to trigger blending on a specific URI. To achieve this, first converter should return non-null string array on certain parameters.
```

**Comment by un-tone** [comment] 2017-07-31 14:00
It is definitely a good feature, but it doesn't suit for this case since the Website app can't know is there registered handler for this URI `/content/dynamic/something` or this one `/content/dynamic/{?}` or maybe even this `/content/{?}/{?}` when mapping with `Blender.MapUri("/content/dynamic/something", "websiteprovider%y%z");`.
It would be helpful to have a method like `Handler.GetHandlerInfo(string uri)` to be able to get the handler template and other useful info.

**Comment by alemoi** [comment] 2017-07-31 16:33
Sure! I'm working on this one atm: https://github.com/Starcounter/Home/issues/99

**Comment by un-tone** [comment] 2017-07-31 16:58
It's great! Would be really useful.
But now I think it will not help us much in case when Website is started first and `/content/dynamic/{?}` is not registered yet. So there should be another way. I think the best one currently is "to wrap such custom URIs callings into another dynamically created one" as I wrote above.

**Comment by alemoi** [comment] 2017-08-01 10:25
I'm now working on the solution to support blending of concrete URIs, not only handlers as it is now. Hope this will ultimately solve your problem @un-tone

**Comment by alemoi** [comment] 2017-08-01 17:03
> In this case we want that /content/dynamic/{?} handler with something parameter will be called.

Would it solve the problem if you create another handler `Handle.GET("/content/predefined/dynamic/something") {
Self.GET("/content/dynamic/something");
}` that is mapped to needed token? So by basically defining extra handler.

**Comment by un-tone** [comment] 2017-08-01 18:28
Yes, I think so, and that is what I proposed above :smiley:

**Comment by alemoi** [comment] 2017-08-02 23:57
@un-tone I have a build for you, if you want to test the ability to blend specific URIs: http://downloads.starcounter.com/download/Starcounter/Custom/2.3.1.6887

There are also some API changes (renames) and additions: https://github.com/Starcounter/level1/commit/e07502665a81844a587ab9a4981c11e1ca7dc02f

**Comment by un-tone** [comment] 2017-08-04 13:06
I checked the case with the custom SC build. It still doesn't call the specific URI (`/content/dynamic/something`). @alemoi, some clues?

The API changes and additions looks good for me 👍

**Comment by alemoi** [comment] 2017-08-04 14:18
> I checked the case with the custom SC build. It still doesn't call the specific URI (/content/dynamic/something). @alemoi, some clues?

Can you please paste the code that does registration of this specific URI with Blender?

**Comment by un-tone** [comment] 2017-08-07 10:15
```csharp
Blender.MapUri(webMap.ForeignUrl, token, false, true);
```

**Comment by alemoi** [comment] 2017-08-07 11:04
Thanks! And the reproduction scenario is exactly the same as on very top?

**Comment by un-tone** [comment] 2017-08-07 11:33
@alemoi yes

**Comment by un-tone** [comment] 2017-08-07 16:27
### Prerequisites

- Clean SC database
- [SC 2.3.1.6892 version](http://downloads.starcounter.com/download/Starcounter/Custom/2.3.1.6892)

### Steps to reproduce

1. Run **Content** app from `develop` branch (https://github.com/StarcounterApps/Content/commit/5407625349274b39d81bf5c5e68b5d1cdf8b27c5).
1. Run **WebsiteEditor** and **WebsiteProvider** apps from `updated-blender-api` branch (a6a61231019b0a42c95c27adb3a6544798f4b47f).
1. Run **SignIn** app from `develop` branch (https://github.com/StarcounterApps/SignIn/commit/a46d297a1393b64a2002e8c9ed8da177c6a748a4).
1. Go to <http://localhost:8080/signin/generateadminuser>.
1. Go to <http://localhost:8080/signin/signinuser> and log in.
1. Go to <http://localhost:8080/websiteeditor>.
1. Select "DefaultSurface" and go to "Blending points" menu item.
1. Select "TopBar" list item and add a new pinning rule with `/content/dynamic/something` pin URI.
1. Save changes.
1. Put breakpoint in [Content/Api/ContentHandlers.cs#L17](https://github.com/StarcounterApps/Content/blob/develop/src/Content/Api/ContentHandlers.cs#L17) and attach debugger to `sccode` process.
1. Go to <http://localhost:8080/websiteeditor>.

### Expected result

Hit the breakpoint.

### Actual result

It doesn't hit the breakpoint.

-----

@warpech could you please check this case too since result of the case described on the top are different on my and @alemoi dev envs. I tried to describe it more detailed here.

**Comment by Mihaiii** [comment] 2017-08-07 16:46
I tried it with that SC version and those checkouts and it doesn't hit the breakpoint. :(

**Comment by Mihaiii** [comment] 2017-08-07 16:50
...and now it works. Let me get a scenario.

**Comment by Mihaiii** [comment] 2017-08-07 16:53
All I know for now is that I tried to change the `order` from `0` to `2`, I got the following error (see pic), refreshed the page, and at refresh it hit the breakpoint.

Will try it all over from the beginning.
<img width="960" alt="website" src="https://user-images.githubusercontent.com/8951553/29036913-bf4f6ddc-7ba1-11e7-8b70-a6ea8f85905f.png">

**Comment by un-tone** [comment] 2017-08-07 16:57
@Mihaiii There is some breaking changes in Blender for Website app in this custom SC build. So please don't play with changing pinning rules for now :smile:. I've already reported about this issue.

**Comment by Mihaiii** [comment] 2017-08-07 16:58
I wasn't about to make a new issue :))))

**Comment by Mihaiii** [comment] 2017-08-07 17:03
It will take more than expecting to try it over. Assertation failed, VS not responding etc :))))

<img width="359" alt="assertationfailed" src="https://user-images.githubusercontent.com/8951553/29037229-02be7ec2-7ba3-11e7-8977-af17683f1725.png">

**Comment by Mihaiii** [comment] 2017-08-07 17:12
@un-tone Could you please stop all your apps and rerun them? (with `/content/dynamic/something` already being in the db)

**Comment by Mihaiii** [comment] 2017-08-07 17:18
Sorry, not all of them. Just restart Content App.

**Comment by un-tone** [comment] 2017-08-07 17:21
Yes, I see, in this way it works. I'll investigate it. Thanks!

**Comment by Mihaiii** [comment] 2017-08-07 17:22
If I start Content app first, it doesn't work. If I start I last, it works.
No problem. Let me know if I can do anything else!

**Comment by un-tone** [comment] 2017-08-08 11:31
The issue with changing of pinning rules is fixed in the last RC SC build.

**Comment by un-tone** [comment] 2017-08-08 12:12
I refreshed the steps https://github.com/StarcounterApps/Website/issues/154#issuecomment-320712188.

There are 2 cases (order of apps starting does matter):

1. Described above in the steps:

```
Blender.GetRunCandidatesForUri(uri).Select(x => x.Uri)
    [0]: "/content/dynamic/something"
    [1]: "/websiteprovider/blender/surface/B/point/C"

Blender.GetRunCandidatesForUri(uri).Select(x => x.HandlerUri)
    [0]: null
    [1]: "/websiteprovider/blender/surface/b/point/c"
```

2. When a specific URI is already mapped by WebsiteProvider and Content app is started after WebsiteProvider:

```
Blender.GetRunCandidatesForUri(uri).Select(x => x.Uri)
    [0]: "/content/dynamic/something"
    [1]: "/websiteprovider/blender/surface/B/point/C"

Blender.GetRunCandidatesForUri(uri).Select(x => x.HandlerUri)
    [0]: "/content/dynamic/{?}"
    [1]: "/websiteprovider/blender/surface/b/point/c"
```

-----

So we can see that `HandlerUri` is not initialized in the issue case. Please look at this, @alemoi.

**Comment by un-tone** [comment] 2017-08-11 08:02
ping @alemoi

**Comment by alemoi** [comment] 2017-08-13 00:58
Gracias señor @un-tone! Very nice reproduction description. The issue is fixed, please verify. In latest nightly.

**Comment by un-tone** [comment] 2017-08-15 08:24
It works perfect! Thank you @alemoi

**Closed by un-tone** 2017-08-15 08:24 UTC
Labels: bug, WebsiteProvider
