### ISSUE TITLE
Pinning rule inserts response mapped in another surface

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#128] opened 2017-07-06 14:52 UTC
### Steps to reproduce

1. Start WebsiteEditor, WebsiteProvider https://github.com/StarcounterApps/Website/commit/ca199025da05ef61b894223d45b470d4ae912f2f
2. Start Content https://github.com/StarcounterApps/Content/commit/927b812677475a351f29b03c496c9faea74b9bfd
3. Start SignIn https://github.com/StarcounterApps/SignIn/commit/ebe41c9856e97b887dfa2b67c9271e78ff2d36e6
4. Reset website rules by going to http://localhost:8080/websiteeditor/resetdata
5. Go to http://localhost:8080/websiteeditor

### Expected result

You should see only Sign In output in the top bar.

### Actual result

You see Sign In and "Content not found" response from the top bar.

The reason is that even though you are in `DefaultSurface`, WebsiteProvider executes the rule that was configured for `HolyGrailSurface`.

### Screenshot

![2017-07-06 16_51_42-websiteeditor](https://user-images.githubusercontent.com/566463/27917166-8165a8f0-626b-11e7-8433-7f2c04d568d9.png)

**Comment by Mihaiii** [comment] 2017-07-06 18:44
Had a look into this to celebrate a proper debugging session after a log time, but now I see that un-tone self-assigned and I'll stop (this and the fact that I still don't really know the technical details about blending). So to not feel like I lost some time for nothing: 
- at least all the Pin URIs that start with "content/dynamic/" from are called.

**Comment by Mihaiii** [comment] 2017-07-06 18:46
Had a look into this to celebrate a proper debugging session after a log time, but now I see that un-tone self-assigned and I'll stop (this and the fact that I still don't really know the technical details about blending). So to not feel like I lost some time for nothing:

- at least all the Pin URIs that start with `content/dynamic/` from are called.
- both DefaultSurface and HolyGrailSurface have `/signin/user` as Pin URI. If you change the Pin Uri from the DefaultSurface to something else, the unwanted behavior doesn't happen.

**Comment by un-tone** [comment] 2017-07-07 18:29
There is an unexpected behavior from the Blender.
For both cases with DefaultSurface and HolyGraleSurface are used different blending tokens But it doesn't matter for some reason.

In debug mode before calling `Self.GET(uri)` where `uri` equals to `/WebsiteEditor/blender/surface/B6/point/B7` I checked Blender mappings:
```
Blender.ListAll().Where(x => x.Key == "websiteeditor%B6%B7").SelectMany(x => x.Value)
{System.Linq.Enumerable.<SelectManyIterator>d__16<System.Collections.Generic.KeyValuePair<string, string[]>, string>}
    [0]: "/WebsiteEditor/blender/surface/B6/point/B7"
    [1]: "/signin/user"
Blender.ListAll().Where(x => x.Value.Contains("/WebsiteEditor/blender/surface/B6/point/B7")).Select(x => x.Key)
{System.Linq.Enumerable.WhereSelectEnumerableIterator<System.Collections.Generic.KeyValuePair<string, string[]>, string>}
    [0]: "websiteeditor%B6%B7"
```
Here `websiteeditor%B6%B7` is the blending token for case with DefaultSurface and the provided data is correct since I expect to get data only from `/signin/user` resource.

But `Self.GET(uri)` calls apparently all other registered URIs and generated "empty" ones from the Pinning Rules (and mapped with Blender):
![image](https://user-images.githubusercontent.com/1625378/27970587-157ea9e6-6358-11e7-98a6-5693200d53d3.png)
Calling URIs:
```
"/WebsiteEditor/blender/surface/B6/point/B7"
"/signin/user"
"/content/dynamic/navigation"
"/WebsiteEditor/blender/surface/CE/point/CG"
"/content/dynamic/userprofile/header"
"/WebsiteEditor/blender/surface/CE/point/CG/uri/CM"
"/content/dynamic/apps/header"
"/content/dynamic/apps/footer"
"/WebsiteEditor/blender/surface/CE/point/CG/uri/CL"
...
...
```

----

Using Blender I expect that if I call a URI which was mapped using some tokens, it will call only those URIs which was mapped exactly and only with that tokens.
In current case the app calls `/WebsiteEditor/blender/surface/B6/point/B7` which was mapped only with token `websiteeditor%B6%B7`. So I expect that Blender will call only `/signin/user` URI additionally.

@alemoi could you please look at this issue?

**Comment by alemoi** [comment] 2017-07-10 15:07
Its like this URI "/WebsiteEditor/blender/surface/X/point/Y" is blended with "/signin/user" which is correspondingly blended with:
![image](https://user-images.githubusercontent.com/208134/28024466-14527a58-6591-11e7-81f5-1258421f7fe4.png)

So the last blended URIs are called in a chained recursive manner (even if they are blended with different tokens). It was the idea for blender originally, to call URIs recursively.

I already removed this behavior, but reverted it back because wasn't sure it solves the problem (there was some bug I was solving).

My proposal now, is to call all handlers for all tokens for given handler, but not recursively. In the above example it means that "GET /signin/user" will be called, but it won't call handlers blended to it.

WGYT @un-tone @warpech

**Comment by un-tone** [comment] 2017-07-10 15:10
Agree. The proposed behavior is what I exactly expected.

**Comment by alemoi** [comment] 2017-07-10 15:21
In this case we abandon the original idea of "chained" or "recursive" blending. Is that ok with @warpech and @miyconst ?

**Comment by alemoi** [comment] 2017-07-10 15:25
As i said, I already pushed this fix a while ago, but reverted it, because of no use. Here is the fix: https://github.com/Starcounter/level1/commit/c04b963252bc001c6bf9bc50e55a7e5328f09665

**Comment by alemoi** [comment] 2017-07-10 17:29
In any case I just have pushed the fix into 2.3 and develop. @un-tone you can test tomorrow how its working out for you! Thanks!

**Comment by un-tone** [comment] 2017-07-11 08:31
Thanks @alemoi ! I tested and it works well. Furthermore, it fixed this issue https://github.com/StarcounterApps/SignIn/issues/115 too.
Closing as done...

**Closed by un-tone** 2017-07-11 08:31 UTC
Labels: bug, P/High, project:CS, WebsiteProvider

**Comment by alemoi** [comment] 2017-07-12 13:41
Updated the documentation on the matter.

**Comment by warpech** [comment] 2017-07-12 13:50
Could you pls paste a link here?

**Comment by alemoi** [comment] 2017-07-12 14:30
Its no big deal, I just replaced info about chained calls into a new sentence: https://docs.starcounter.io/v/RC/guides/blending/blending/

**Comment by warpech** [comment] 2017-07-12 15:25
Link to the commit: https://github.com/Starcounter/Docs/commit/c727454b418871cfabf005cf68ca727bb909fc2a
