### ISSUE TITLE
WebsiteProvider does not start with Starcounter Release 2.3.0.6350

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Website#108] opened 2017-06-07 07:41 UTC
@un-tone could you please investigate?

### Steps to reproduce

1. Call `build.bat` on master branch
2. Call `run.bat`

### Expected result

The app should start

### Actual result

There is an error:

```
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. ScErrHandlerAlreadyRegistered (SCERR13003): This handler has already been registered. GET /website/blender/surface/i/point/j on port 8080
Version: 2.3.0.6350.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR13003.
Version: 2.3.0.6350.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR4259.
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 563
   at Starcounter.Hosting.Package.ProcessWithinCurrentApplication(Application application, ApplicationDirectory applicationDir) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 265
   at Starcounter.Hosting.Package.Process() in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 138
   at Starcounter.Hosting.Package.Process(IntPtr hPackage) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 55
   at StarcounterInternal.Hosting.Processor.RunMessageLoop(Void* hsched) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Hosting\Starcounter.Hosting\Processor.cs:line 89
ErrorCode=4259
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR4259
---> System.Exception: ScErrHandlerAlreadyRegistered (SCERR13003): This handler has already been registered. GET /website/blender/surface/i/point/j on port 8080
Version: 2.3.0.6350.
Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR13003.
   at Starcounter.Rest.UserHandlerInfo.TryAddProxyOrReplaceDelegate(Func`4 userDelegate, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 646
   at Starcounter.Rest.UriHandlersManager.RegisterUriHandler(UInt16 port, String methodSpaceUri, Byte[] nativeParamTypes, Type messageType, Func`4 wrappedDelegate, NetworkProtocolType protoType, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 894
   at Starcounter.Rest.UriManagedHandlersCodegen.RegisterDelegate(UInt16 port, String methodSpaceUri, MethodInfo userDelegateInfo, Expression delegExpr, NetworkProtocolType protoType, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 613
   at Starcounter.Rest.UriManagedHandlersCodegen.GenerateParsingDelegate(UInt16 port, String methodSpaceUri, Func`1 userDelegate, HandlerOptions ho, NetworkProtocolType protoType) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Rest\UriManagedHandlersCodegen.cs:line 856
   at Starcounter.Rest.RestRegistrationProxy.RegisterHandler(UInt16 port, String methodSpaceUri, Func`1 handler, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Rest\RestInitialization.cs:line 59
   at Starcounter.Handle.GET(String uriTemplate, Func`1 code, HandlerOptions ho) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Starcounter.Internal\Handle.GET.cs:line 115
   at WebsiteProvider.MappingHandlers.RegisterEmptyHandler(String uri) in C:\www\Website\src\WebsiteProvider\Api\MappingHandlers.cs:line 105
   at WebsiteProvider.MappingHandlers.MapPinningRule(WebMap webMap, String registeredSectionUri) in C:\www\Website\src\WebsiteProvider\Api\MappingHandlers.cs:line 49
   at WebsiteProvider.MappingHandlers.Register() in C:\www\Website\src\WebsiteProvider\Api\MappingHandlers.cs:line 22
   at WebsiteProvider.Program.Main() in C:\www\Website\src\WebsiteProvider\Program.cs:line 11
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\TeamCity\BuildAgent\work\sc-4933\Level1\src\Hosting\Starcounter.Hosting\Package.cs:line 529
HResult=-2146233088
HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR13003
```

##### Involved apps' version

StarcounterApps/Website@cdc197ec7f4ed86b1c0a0d597c505485b60bf833
 
### Screenshot

![2017-06-07 09_41_10-command prompt](https://user-images.githubusercontent.com/566463/26867407-7be694ce-4b65-11e7-8408-72d3267b3811.png)

**Comment by un-tone** [comment] 2017-06-07 08:07
The error message is `(SCERR13003): This handler has already been registered. GET /website/blender/surface/i/point/j on port 8080`. In the code there is such condition `if (!Handle.IsHandlerRegistered(uri, selfOnlyOptions))` before registering a handler. In 2.3.1 builds it works correctly, but in 2.3.0.6350 for some reason not.

**Comment by warpech** [comment] 2017-06-07 08:23
Thanks so much for the investigation.

@alemoi could you pls take a look? Anything we can do to fix in the Website app, or will it simply not work for 2.3.0.6350?

**Comment by alemoi** [comment] 2017-06-07 11:56
So the problem is that `Handle.IsHandlerRegistered` is not working for `2.3.0.6350` correct?

**Comment by un-tone** [comment] 2017-06-07 14:01
Right

**Comment by alemoi** [comment] 2017-06-07 14:22
What are the values of `uri` and `selfOnlyOptions` in `if (!Handle.IsHandlerRegistered(uri, selfOnlyOptions))`? Thanks.

**Comment by un-tone** [comment] 2017-06-07 14:28
```
private readonly HandlerOptions selfOnlyOptions = new HandlerOptions {SelfOnly = true};
```
```
if (!Handle.IsHandlerRegistered(uri, selfOnlyOptions))
{
    Handle.GET(uri, () => new Json(), selfOnlyOptions);
}
```
`uri` is equal to `/website/blender/surface/i/point/j` and was generated in this code https://github.com/StarcounterApps/Website/blob/develop/src/WebsiteProvider/Helpers/MappingExtensions.cs#L24-L29

**Comment by alemoi** [comment] 2017-06-07 14:50
Thanks!

1. Strange that you are registering a handler for a specific URI `/website/blender/surface/i/point/j`. Is that correct? I would expect smth like `/website/blender/surface/{?}/point/{?}`

2. Try not to pass `selfOnlyOptions` to `IsHandlerRegistered`? Just some `new HandlerOptions()`

**Comment by un-tone** [comment] 2017-06-07 15:04
1. That is correct. We need to register such "empty" handlers for each "surface-section-uri" combination.
2. I'm getting the same error.

**Comment by alemoi** [comment] 2017-06-08 10:17
> That is correct. We need to register such "empty" handlers for each "surface-section-uri" combination.

Can you please copy the list of registered URIs here, at the point before the check is made? From: http://127.0.0.1:8181/#/server/network

**Comment by warpech** [comment] 2017-06-08 10:29
@alemoi I guess the simplest way is to reproduce by yourself using the steps at https://github.com/StarcounterApps/Website/issues/108#issue-234119570. `run.bat` starts WebsiteProvide, which is the app that sets the handlers.

**Comment by alemoi** [comment] 2017-06-08 10:52
Sure, started doing that. 
However, should I take the `develop` branch or `simpler-provider` ?
```
Steps to reproduce

Call build.bat on develop branch
Call run.bat
```
`develop` does not seem to have such.

**Comment by warpech** [comment] 2017-06-08 12:39
`develop` branch has these scripts for sure: 

- https://github.com/StarcounterApps/Website/blob/develop/build.bat
- https://github.com/StarcounterApps/Website/blob/develop/run.bat

**Comment by warpech** [comment] 2017-06-08 12:40
I have changed the description to say `master` branch. Anyway, all branches have these scripts for sure. They were synced recently:

- https://github.com/StarcounterApps/Website/blob/master/build.bat
- https://github.com/StarcounterApps/Website/blob/master/run.bat

**Comment by alemoi** [comment] 2017-06-08 14:13
Sorry, I wasn't clear. I couldn't see the URI handler containing `/website/blender/surface` that is registered upon start up.

**Comment by un-tone** [comment] 2017-06-08 14:28
The URI is generated dynamically. Starcounter Administrator doesn't show mapped URIs with `SelfOnly = false` so to get the list I changed this property to `true`.

There are the following URIs which I got before the app throwed an exception:
![image](https://user-images.githubusercontent.com/1625378/26933583-9a5c89c6-4c6f-11e7-8c0b-23cdbe36849b.png)

The exception message:
```
System.Exception: 'ScErrHandlerAlreadyRegistered (SCERR13003): This handler has already been registered. GET /website/blender/surface/i/point/j on port 8080
```

**Comment by alemoi** [comment] 2017-06-09 09:59
I found the reason. The format for `Handle.IsHandlerRegistered` is `method_space_uri`, which is ugly, i understand, need to change it to 2 parameters instead, method and URI. Here is the fixed code for now:
```
            if (!Handle.IsHandlerRegistered("GET " + uri, selfOnlyOptions))
            {
                Handle.GET(uri, () => new Json(), selfOnlyOptions);
            }
```

In 2.3.1 the handlers are automatically overwritten on same registration, so there is no error.

**Comment by un-tone** [comment] 2017-06-09 14:21
Thank you @alemoi!
I created PR https://github.com/StarcounterApps/Website/pull/111

**Comment by alemoi** [comment] 2017-06-10 21:01
As promised made this version of `IsHandlerRegistered` deprecated. Added another version: https://github.com/Starcounter/level1/commit/5bfe727126ce50901b44a722b8f9ef2abab8d24d

**Comment by un-tone** [comment] 2017-06-21 18:43
Great! I made changes for 2.3.1 version and created PR https://github.com/StarcounterApps/Website/pull/117

**Comment by un-tone** [comment] 2017-07-04 15:09
Current issue is resolved. Closing

**Closed by un-tone** 2017-07-04 15:09 UTC
Labels: bug
